<?php
header('Access-Control-Allow-Origin: *');
?>
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ministerio de Salud de San Juan</title>

    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/select2.css">
    <script src="js/jquery.min.js"></script>
    <script src="js/user.js"></script>
</head>
<body>
<div class="container container-fluid">

    <div class="row">
        <table class="esqueleto table table-sm table-responsive-sm table-responsive-md table-responsive-lg text-center">
            <tr class="mainbannerrow card-3 secundario">
                <td colspan="4">
                    <div class="row">
                        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10 text-left">
                            <img src="img/mainBanner.svg" class="img-fluid mainbanner" alt="Responsive image">
                        </div>
                        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2 ">
                            <button id="book" class="btn btn-sm btn-outline-light text-right"><span class="glyphicon"><img src="img/heart.svg"> </span> Agregar a favoritos</button>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <div class="row">
                        <br>
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                            <br>
                            <div id="noticias" class="card-2 secundario text-left">
                                <h5 id="titulonoticia"> Sección de avisos</h5>
                                <p id="textonoticia">En este espacio aparecerán avisos importantes.</p>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="notcontainer">
                        <img src="img/gedoc.png" class="img-thumbnail axx card-1" data-nombre="gedoc">
                        <div class="notcontent">
                            <h4>Gedoc</h4>
                        </div>
                    </div>
                    <!--<img src="img/gedoc.png" class="img-thumbnail axx card-1" alt="Responsive image" data-nombre="gedoc">-->
                </td>
                <td>
                    <div class="notcontainer">
                        <img src="img/gedoc.png" class="img-thumbnail axx card-1" data-nombre="siged">
                        <div class="notcontent">
                            <h4>SiGed</h4>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="notcontainer">
                        <img src="img/mesadeentrada.png" class="img-thumbnail axx card-1" data-nombre="mesadeentrada">
                        <div class="notcontent">
                            <h4>Mesa de entrada</h4>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="notcontainer">
                        <img src="img/nutricion.png" class="img-thumbnail axx card-1" data-nombre="nutricion">
                        <div class="notcontent">
                            <h4>Nutrición</h4>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="notcontainer">
                        <img src="img/regprof.png" class="img-thumbnail axx card-1" data-nombre="regprof">
                        <div class="notcontent">
                            <h4>Registro de profesionales</h4>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="notcontainer">
                        <img src="img/otrs.png" class="img-thumbnail axx card-1" data-nombre="otrs">
                        <div class="notcontent">
                            <h4>O.T.R.S</h4>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="notcontainer">
                        <img src="img/permisosinternet.png" class="img-thumbnail axx card-1" data-nombre="permisosinternet">
                        <div class="notcontent">
                            <h4>Permisos para internet</h4>
                        </div>
                    </div>
                </td>
                <td>
                    <div class="notcontainer">
                        <img src="img/email.png" class="img-thumbnail axx card-1" data-nombre="email">
                        <div class="notcontent">
                            <h4>Email oficial</h4>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="4"></td>
            </tr>
        </table>
    </div>
    <br>

    <div class="row card-2 secundario formulario">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
            <h5>Si tiene algún problema o consulta informática, complete el siguiente formulario:</h5>
            <form onsubmit="return false;">
                <div class="form-group">
                    <br>
                    <label for="nombre">Nombre:</label>
                    <input type="text" class="form-control" id="nombre" placeholder="nombre completo"  data-toggle="tooltip" data-placement="top" title="Tooltip on top">
                </div>
                <div class="form-group">
                    <label for="customer">Lugar:</label>
                    <select id="customer" style="width: 100%">
                    </select>
                </div>
                <div class="form-group">
                    <label for="telefono">Teléfono:</label>
                    <input type="number" class="form-control" id="telefono" placeholder="número de teléfono personal o interno" >
                </div>
                <div class="form-group">
                    <label for="tipo">Seleccione tipo de problema:</label>
                    <select id="tipo" style="width: 100%">
                    </select>
                </div>
                <div class="form-group">
                    <label for="comentario">Explique brevemente su problema:</label>
                    <textarea class="form-control" id="comentario" rows="3" maxlength="240" ></textarea>
                </div>
                <div class="form-group">
                    <button id="enviar" class="btn btn-block btn-success">Enviar</button>
                </div>
            </form>
            <br>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-box card-4 modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!--Contenido dinámico-->
                </div>
                <div class="modal-footer">
                    <!--<button type="button" class="btn btn-danger btnmodal" data-dismiss="modal">Cerrar</button>-->
                    <button type="button" class="ir btn btn-success btnmodal"  data-dismiss="modal">Entrar</button>
                </div>
            </div>
        </div>
    </div>

    <br><br><br>

    <div class="footer">
        <p>División de Informática del Ministerio de Salud de San Juan</p>
    </div>

</div>


</body>

<script src="js/bootstrap.js"></script>
<script src="js/popper.js"></script>
<script src="js/select2.js"></script>

</html>