<!--
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Slim</h1>
        <div>a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
        <?php endif; ?>
    </body>
</html>
-->

<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ministerio de Salud de San Juan</title>

    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/jquery.min.js"></script>
</head>
<body>
<div class="container container-fluid">

<div class="row">
    <table class="esqueleto table table-sm table-responsive-sm table-responsive-md table-responsive-lg">
        <tr class="mainbannerrow card-3 secundario">
            <td colspan="4">
                <img src="img/mainBanner.svg" class="img-fluid mainbanner" alt="Responsive image">
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <div class="row">
                    <br>
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
                        <br>
                        <div class="card-2 secundario">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam cumque debitis distinctio expedita, hic minima nisi. Animi, culpa cupiditate eligendi excepturi fugit laudantium minima omnis porro quasi quibusdam ut vitae!</p>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <img src="img/gedoc.png" class="img-thumbnail axx card-1" alt="Responsive image" data-nombre="gedoc">
            </td>
            <td>
                <img src="img/gedoc.png" class="img-thumbnail axx card-1" alt="Responsive image">
            </td>
            <td>
                <img src="img/gedoc.png" class="img-thumbnail axx card-1" alt="Responsive image">
            </td>
            <td>
                <img src="img/gedoc.png" class="img-thumbnail axx card-1" alt="Responsive image">
            </td>
        </tr>
        <tr>
            <td>
                <img src="img/gedoc.png" class="img-thumbnail axx card-1" alt="Responsive image">
            </td>
            <td>
                <img src="img/gedoc.png" class="img-thumbnail axx card-1" alt="Responsive image">
            </td>
            <td>
                <img src="img/gedoc.png" class="img-thumbnail axx card-1" alt="Responsive image">
            </td>
            <td>
                <img src="img/gedoc.png" class="img-thumbnail axx card-1" alt="Responsive image">
            </td>
        </tr>
        <tr>
            <td colspan="4"></td>
        </tr>
    </table>
</div>
    <br>

    <div class="row card-2 secundario">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
            <form>
                <div class="form-group">
                    <br>
                    <label for="exampleFormControlInput4">Nombre:</label>
                    <input type="text" class="form-control" id="exampleFormControlInput4" placeholder="nombre completo" required>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlInput5">Teléfono:</label>
                    <input type="number" class="form-control" id="exampleFormControlInput5" placeholder="número de teléfono personal o interno" required>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Seleccione tipo de problema:</label>
                    <select class="form-control" id="exampleFormControlSelect1" >
                        <option>Otro</option>
                        <option>Problema técnico</option>
                        <option>Problema de configuración</option>
                        <option>Pedido de insumo informático</option>
                        <option>Se cayó turnos de nuevo</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="exampleFormControlTextarea1">Explique brevemente su problema:</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" required></textarea>
                </div>
                <div class="form-group">
                    <button class="btn btn-block btn-success">Enviar</button>
                </div>
            </form>
            <br>
        </div>

    </div>

    <!-- Modal -->
    <div class="modal fade" id="detailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!--Contenido dinámico-->
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                    <button type="button" class="ir btn btn-success"  data-dismiss="modal">Entrar</button>
                </div>
            </div>
        </div>
    </div>
    <br><br><br>
    <div class="footer">
        <p>Dirección de informática y bla bla</p>
    </div>

</div>


</body>

<script src="js/bootstrap.js"></script>
<script src="js/user.js"></script>
</html>