<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Teléfonos útiles</title>


    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/select2.css">
    <script src="js/jquery.min.js"></script>



</head>
<body>

<div class="container">

    <h3>Teléfonos útiles</h3>

    <br>
    <button id="btnNuevo" class="btn btn-success">Agregar nuevo número</button>
    <br>
    <br>
    <h6>Búsqueda</h6>
    <!--<select id="telefonos" style="width: 100%"></select>-->
    <br>
    <br>

    <table id="telefonos" class="table table-dark table-responsive-sm table-responsive-md table-responsive-lg text-center">
        <thead>
        <tr>
            <th scope="col">Lugar</th>
            <th scope="col">Teléfonos</th>
        </tr>
        </thead>
        <tbody id="telefonosbody">

        </tbody>
    </table>

</div>



<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-box card-4 modal-content">
            <div class="modal-header">
                <h5 class="modal-title"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!--Contenido dinámico-->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btnmodal" data-dismiss="modal">Cerrar</button>
                <button type="button" id="aceptar" class="btn btn-success btnmodal"  data-dismiss="modal">Aceptar</button>
            </div>
        </div>
    </div>
</div>


</body>

<script src="js/bootstrap.js"></script>
<script src="js/popper.js"></script>
<script src="js/select2.js"></script>
<script src="js/telefonos.js"></script>

</html>