<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ministerio de Salud de San Juan</title>

    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/bootstrap-table.min.js"></script>
</head>
<body>
<div class="container-fluid">

        <table class="display table table-bordered" id="clienti" >
            <thead>
            <tr>
                <th data-field="nticket">Nº Ticket</th>
                <th data-field="prioridad">Prioridad</th>
                <th data-field="fechahora">Fecha y Hora</th>
                <th data-field="oficina">Oficina</th>
                <th data-field="motivo">Motivo</th>
                <!--<th data-field="detalle">Detalle</th>-->

            </tr>
            </thead>
        </table>
</div>


<script type="text/javascript">


    $(document).ready(function(){
        $.ajax({
            url: 'getTickets',
            dataType: 'json',
            success: function(data) {
                //alert('done');
                $('#clienti').bootstrapTable({
                    data: data
                });
                $(".fixed-table-loading").hide();
            },
            error: function(e) {
                console.log(e.responseText);
            }
        });
    });
</script>
</body>




</html>