<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ministerio de Salud de San Juan</title>

    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/style.css">
    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="js/bootstrap-table.min.js"></script>
    <link rel="icon" type="image/png" href="ico/favicon.png" />
</head>
<body>
<div class="container-fluid">

    <table id="ttable" class="table table-hover table-dark no-wrap">
        <thead>
        <tr>
            <th width="10%" scope="col">Asignado</th>
            <th width="10%" scope="col">Creado</th>
            <th width="10%" scope="col">Oficina</th>
            <th width="20%" scope="col">Motivo</th>
            <th width="50%" scope="col">Detalle</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>


<script type="text/javascript">

    function loadTickets()
    {
        console.log("load");
        $.ajax({
            url: 'getTickets',
            dataType: 'json',
            success: function(data) {
                //alert('done');

                $('#ttable tbody').empty()

                for (var i=0 ; i<data.length;i++) {

                    var xclass ="";

                    switch (data[i].prioridad)
                    {
                        case 'Muy Baja':
                        {
                            xclass = "bg-primary textBG";
                        }break;

                        case 'Baja':
                        {
                            xclass = "bg-secondary textBG";
                        }break;

                        case 'Normal':
                        {
                            xclass = "bg-success textBG";
                        }break;

                        case 'Alta':
                        {
                            xclass = "bg-warning  blink";
                        }break;

                        case 'Urgente':
                        {
                            xclass = "bg-danger  blink ";
                        }break;

                    }
                    var tmp = '<tr class="'+ xclass +'">' +
                        '<td ><a target="_blank" href="http://otrsminsalud.sanjuan.gob.ar/otrs/index.pl?Action=AgentTicketZoom;TicketID='+data[i].id+'">' + data[i].user + '</a></td>' +
                        '<td ><a target="_blank" href="http://otrsminsalud.sanjuan.gob.ar/otrs/index.pl?Action=AgentTicketZoom;TicketID='+data[i].id+'">' + data[i].fechahora + '</a></td>' +
                        '<td ><a target="_blank" href="http://otrsminsalud.sanjuan.gob.ar/otrs/index.pl?Action=AgentTicketZoom;TicketID='+data[i].id+'">' + data[i].oficina.replace('"','').replace('"','').replace(',','') + '</a></td>' +
                        '<td ><a target="_blank" href="http://otrsminsalud.sanjuan.gob.ar/otrs/index.pl?Action=AgentTicketZoom;TicketID='+data[i].id+'">' + data[i].motivo + '</a></td>' +
                        '<td ><a target="_blank" href="http://otrsminsalud.sanjuan.gob.ar/otrs/index.pl?Action=AgentTicketZoom;TicketID='+data[i].id+'">' + data[i].detalle + '</a></td></tr>';

                    $('#ttable tbody').append(tmp)
                }

            },
            error: function(e) {
                console.log(e.responseText);
            }
        });
    }
    $(document).ready(function(){

        setInterval(function(){
        loadTickets()
        },5000)
    });

/*
    $(document).ready(function(){
        $.ajax({
            url: 'getTickets',
            dataType: 'json',
            success: function(data) {
                //alert('done');
                $('#clienti thead').addClass("bg-warning");
                $('#clienti').bootstrapTable({
                    data: data
                });
                $(".fixed-table-loading").hide();
            },
            error: function(e) {
                console.log(e.responseText);
            }
        });
    });
    */
</script>
</body>



</html>
